const S={mode:"individual",outfit:JSON.parse(localStorage.getItem("duc-outfit")||"{}"),links:JSON.parse(localStorage.getItem("duc-links")||"[]"),mirror:true,active:null,landmarks:null,image:null,stream:null};
const C=[["top","👕","Shirt / T-shirt","Top"],["bottom","👖","Pants / Jeans","Bottom"],["outerwear","🧥","Jacket / Hoodie","Outerwear"],["shoes","👟","Shoes","Shoes"],["headwear","🧢","Cap / Hat","Headwear"],["glasses","🕶️","Glasses","Accessories"]];
const $=function(s){return document.querySelector(s)},cats=$("#categories"),selected=$("#selectedItems"),count=$("#selectedCount"),video=$("#video"),canvas=$("#overlay"),stage=$("#stage"),ctx=canvas.getContext("2d");
function save(){localStorage.setItem("duc-outfit",JSON.stringify(S.outfit));localStorage.setItem("duc-links",JSON.stringify(S.links))}
function render(){cats.innerHTML=C.map(function(c){return '<button class="category" data-id="'+c[0]+'"><span>'+c[1]+' <b>'+c[2]+'</b><small>'+(S.outfit[c[0]]?.name||"Choose an item")+'</small></span><b>＋</b></button>'}).join("");cats.querySelectorAll(".category").forEach(function(b){b.onclick=function(){openCategory(b.dataset.id)}});let a=Object.entries(S.outfit).filter(function(x){return x[1]});count.textContent=a.length+" item"+(a.length===1?"":"s");selected.className="selected"+(!a.length?" empty":"");selected.innerHTML=a.length?a.map(function(x){let id=x[0],v=x[1],cat=C.find(function(c){return c[0]===id});return '<div class="selected-item"><img class="thumb" src="'+(v.image||placeholder(v.name))+'"><div><strong>'+v.name+'</strong><small>'+cat[3]+'</small></div><button class="remove" data-r="'+id+'">×</button></div>'}).join(""):"Choose items to build your outfit.";selected.querySelectorAll("[data-r]").forEach(function(b){b.onclick=function(){delete S.outfit[b.dataset.r];save();render();draw()}})}
function placeholder(t){return "data:image/svg+xml;charset=utf-8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="80" height="80"><rect width="100%" height="100%" fill="#25252d"/><text x="50%" y="54%" fill="white" text-anchor="middle" font-size="10">'+t.slice(0,12)+'</text></svg>')}
function openCategory(id){S.active=id;let c=C.find(function(x){return x[0]===id});$("#dialogTitle").textContent="Choose "+c[2];$("#options").innerHTML='<button type="button" class="option" data-a="upload"><b>Upload '+c[2]+'</b><small>Use a product image</small></button><button type="button" class="option" data-a="demo"><b>Demo item</b><small>Test the camera overlay</small></button>';$("#options").querySelectorAll(".option").forEach(function(b){b.onclick=function(){if(b.dataset.a==="upload")$("#fileInput").click();else{S.outfit[id]={name:"Demo "+c[2],type:c[3],demo:true};save();render();draw()}$("#dialog").close()}});$("#dialog").showModal()}
$("#fileInput").onchange=function(e){let f=e.target.files[0];if(!f||!S.active)return;let r=new FileReader();r.onload=function(){let c=C.find(function(x){return x[0]===S.active});S.outfit[S.active]={name:f.name.replace(/\.[^.]+$/,""),type:c[3],image:r.result};save();render();draw();e.target.value=""};r.readAsDataURL(f)};
document.querySelectorAll(".tab").forEach(function(b){b.onclick=function(){document.querySelectorAll(".tab").forEach(function(x){x.classList.remove("active")});b.classList.add("active");S.mode=b.dataset.mode}});
$("#saveLinkBtn").onclick=function(){let u=$("#productUrl").value.trim();try{new URL(u)}catch(e){return alert("Enter a valid product URL.")}S.links.push({url:u,at:Date.now()});save();$("#productUrl").value="";$("#status").textContent="Product link saved";setTimeout(function(){$("#status").textContent="Camera preview"},1500)};
async function camera(){try{S.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=S.stream;await video.play();video.style.display="block";$("#placeholder").style.display="none";$("#status").textContent="Live camera";resize();pose()}catch(e){alert("Allow camera access and use HTTPS or localhost.")}}
$("#cameraBtn").onclick=camera;$("#placeholderBtn").onclick=camera;
$("#mirrorBtn").onclick=function(){S.mirror=!S.mirror;video.style.transform=S.mirror?"scaleX(-1)":"scaleX(1)";$("#mirrorBtn").classList.toggle("active",S.mirror)};
$("#clearBtn").onclick=function(){S.outfit={};S.links=[];save();render();draw()};
$("#photoInputBtn").onclick=function(){$("#photoInput").click()};
$("#photoInput").onchange=function(e){let f=e.target.files[0];if(!f)return;let im=new Image();im.onload=function(){S.image=im;video.style.display="none";$("#placeholder").style.display="none";resize();draw()};im.src=URL.createObjectURL(f)};
$("#captureBtn").onclick=savePreview;$("#downloadBtn").onclick=savePreview;
function resize(){let r=stage.getBoundingClientRect(),d=devicePixelRatio;canvas.width=r.width*d;canvas.height=r.height*d;canvas.style.width=r.width+"px";canvas.style.height=r.height+"px";draw()}
window.onresize=resize;
function pose(){if(!window.Pose||S.pose)return;S.pose=new Pose({locateFile:function(f){return "https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5/"+f}});S.pose.setOptions({modelComplexity:0,minDetectionConfidence:.5,minTrackingConfidence:.5});S.pose.onResults(function(r){S.landmarks=r.poseLandmarks||null;draw()});new Camera(video,{onFrame:async function(){return S.pose.send({image:video})},width:1280,height:720}).start()}
function point(i,w,h){let p=S.landmarks?.[i];return p?{x:(S.mirror?1-p.x:p.x)*w,y:p.y*h}:null}
function draw(){let w=canvas.clientWidth,h=canvas.clientHeight,d=devicePixelRatio;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);if(S.image){let sc=Math.max(w/S.image.width,h/S.image.height),iw=S.image.width*sc,ih=S.image.height*sc;ctx.drawImage(S.image,(w-iw)/2,(h-ih)/2,iw,ih)}let p={ls:point(11,w,h),rs:point(12,w,h),lh:point(23,w,h),rh:point(24,w,h),nose:point(0,w,h),lw:point(15,w,h),rw:point(16,w,h)};Object.entries(S.outfit).forEach(function(x){let id=x[0],v=x[1];if(v.image)clothes(id,v.image,p);else demo(id,p)})}
function clothes(id,src,p){let im=new Image();im.onload=function(){let b=box(id,p);if(!b)return;ctx.globalAlpha=.88;ctx.drawImage(im,b.x,b.y,b.w,b.h);ctx.globalAlpha=1};im.src=src}
function box(id,p){if((id==="top"||id==="outerwear")&&p.ls&&p.rs&&p.lh&&p.rh){let sw=Math.hypot(p.rs.x-p.ls.x,p.rs.y-p.ls.y);return{x:(p.ls.x+p.rs.x)/2-sw*1.25,y:(p.ls.y+p.rs.y)/2,w:sw*2.5,h:sw*3}}if(id==="bottom"&&p.lh&&p.rh){let w=Math.abs(p.rh.x-p.lh.x)*2.7+70;return{x:(p.lh.x+p.rh.x)/2-w/2,y:(p.lh.y+p.rh.y)/2-8,w:w,h:Math.max(150,w*1.15)}}if(id==="headwear"&&p.nose)return{x:p.nose.x-55,y:p.nose.y-115,w:110,h:70};if(id==="glasses"&&p.nose)return{x:p.nose.x-55,y:p.nose.y-30,w:110,h:42};if(id==="shoes"&&p.lw&&p.rw)return{x:Math.min(p.lw.x,p.rw.x)-30,y:Math.max(p.lw.y,p.rw.y)-35,w:Math.abs(p.lw.x-p.rw.x)+60,h:45}}
function demo(id,p){let b=box(id,p);if(!b)return;ctx.save();ctx.strokeStyle="#c9ff58";ctx.fillStyle="#c9ff5830";ctx.lineWidth=3;ctx.globalAlpha=.7;if(id==="headwear"){ctx.beginPath();ctx.ellipse(b.x+b.w/2,b.y+b.h/2,b.w/2,25,0,Math.PI,0);ctx.fill();ctx.stroke()}else{ctx.fillRect(b.x,b.y,b.w,b.h);ctx.strokeRect(b.x,b.y,b.w,b.h)}ctx.restore()}
function savePreview(){let o=document.createElement("canvas");o.width=1280;o.height=800;let c=o.getContext("2d");c.fillStyle="#07070a";c.fillRect(0,0,o.width,o.height);let src=S.image||video;if(src&&(S.image||video.readyState>=2)){let sw=src.videoWidth||src.width,sh=src.videoHeight||src.height,sc=Math.max(o.width/sw,o.height/sh),iw=sw*sc,ih=sh*sc;c.save();if(S.mirror&&!S.image){c.translate(o.width,0);c.scale(-1,1)}c.drawImage(src,(o.width-iw)/2,(o.height-ih)/2,iw,ih);c.restore()}c.drawImage(canvas,0,0,o.width,o.height);c.fillStyle="#fff";c.font="700 24px Arial";c.fillText("Dress Up Camera",35,45);let a=document.createElement("a");a.download="dress-up-camera.png";a.href=o.toDataURL("image/png");a.click()}
render();