const API_BASE = (localStorage.getItem("duc-api-base") || "http://localhost:8000").replace(/\/$/, "");
const $ = (s) => document.querySelector(s);
const state = { personData: null, rows: [], stream: null, resultUrl: null };
const categoryOptions = [["top","Shirt / T-shirt"],["bottom","Pants / Jeans"],["outerwear","Jacket / Hoodie"],["one-piece","Dress / One-piece"],["shoes","Shoes"],["headwear","Cap / Hat"],["accessory","Accessory"]];
function fileToDataUri(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
function updateCount(){$("#itemCount").textContent=state.rows.length+" / 5 items";$("#addGarment").disabled=state.rows.length>=5;$("#generate").disabled=!state.personData||!state.rows.length||state.rows.some(x=>!x.imageData)}
function setStatus(text,kind=""){$("#apiStatus").textContent=text;$("#apiStatus").className="status "+kind}
function addRow(category="top"){if(state.rows.length>=5)return;const item={id:crypto.randomUUID(),category,name:"",imageData:null};state.rows.push(item);renderRows();updateCount()}
function renderRows(){const root=$("#garmentRows");root.innerHTML="";state.rows.forEach((item,index)=>{const row=document.createElement("div");row.className="garment-row";const select=document.createElement("select");select.setAttribute("aria-label","Garment category");categoryOptions.forEach(([value,label])=>{const o=document.createElement("option");o.value=value;o.textContent=label;o.selected=value===item.category;select.append(o)});select.onchange=()=>item.category=select.value;const mid=document.createElement("div");const name=document.createElement("input");name.type="text";name.placeholder="Item name (optional)";name.value=item.name;name.oninput=()=>item.name=name.value;const file=document.createElement("input");file.type="file";file.accept="image/*";file.setAttribute("aria-label","Product image");file.onchange=async()=>{const f=file.files?.[0];if(!f)return;item.imageData=await fileToDataUri(f);item.name=item.name||f.name.replace(/\.[^.]+$/,"");file.insertAdjacentHTML("afterend","");renderRows();updateCount()};const small=document.createElement("small");small.textContent=item.imageData?"Image ready ✓":"Upload product image";mid.append(name,file,small);const remove=document.createElement("button");remove.className="remove";remove.textContent="×";remove.title="Remove item";remove.onclick=()=>{state.rows=state.rows.filter(x=>x.id!==item.id);renderRows();updateCount()};row.append(select,mid,remove);root.append(row)})}
$("#addGarment").onclick=()=>addRow();
$("#personFile").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;state.personData=await fileToDataUri(f);$("#personPreview").src=state.personData;$("#personPreview").hidden=false;$("#camera").hidden=true;$("#takePhoto").hidden=true;updateCount()};
$("#cameraOpen").onclick=async()=>{try{state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user"},audio:false});$("#camera").srcObject=state.stream;$("#camera").hidden=false;$("#takePhoto").hidden=false}catch(e){alert("Camera access failed. Allow permission or upload a photo instead.")}};
$("#takePhoto").onclick=()=>{const v=$("#camera"),c=document.createElement("canvas");c.width=v.videoWidth;c.height=v.videoHeight;c.getContext("2d").drawImage(v,0,0);state.personData=c.toDataURL("image/jpeg",.92);$("#personPreview").src=state.personData;$("#personPreview").hidden=false;state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;v.hidden=true;$("#takePhoto").hidden=true;updateCount()};
$("#generate").onclick=async()=>{if(!state.personData||!state.rows.length)return;const btn=$("#generate");btn.disabled=true;$("#resultState").textContent="Generating…";$("#resultPlaceholder").hidden=false;$("#resultPlaceholder").innerHTML="<b>AI is fitting your selected items…</b><p>This can take a minute or longer for a whole outfit. Keep this page open.</p>";$("#resultImage").hidden=true;$("#resultMessage").textContent="";try{const response=await fetch(API_BASE+"/api/try-on",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({person_image:state.personData,garments:state.rows.map((g,i)=>({category:g.category,name:g.name||categoryOptions.find(c=>c[0]===g.category)?.[1]||"Garment "+(i+1),image:g.imageData})),quality:$("#quality").value})});const body=await response.json();if(!response.ok)throw new Error(body.detail||"AI generation failed");state.resultUrl=body.result_image;$("#resultImage").src=body.result_image;$("#resultImage").hidden=false;$("#resultPlaceholder").hidden=true;$("#openResult").href=body.result_image;$("#openResult").hidden=false;$("#saveResult").disabled=false;$("#resultState").textContent="Completed";$("#resultMessage").textContent=body.note||"Generated with "+body.model;setStatus("AI service connected","ok")}catch(e){$("#resultState").textContent="Could not generate";$("#resultPlaceholder").hidden=false;$("#resultPlaceholder").innerHTML="<b>Generation failed</b><p>"+escapeHtml(e.message)+"</p>";setStatus("Check AI service","error")}finally{btn.disabled=false;updateCount()}};
$("#saveResult").onclick=()=>{if(!state.resultUrl)return;const a=document.createElement("a");a.href=state.resultUrl;a.target="_blank";a.rel="noreferrer";a.download="dress-up-camera-ai-result.png";a.click()};
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function checkApi(){try{const r=await fetch(API_BASE+"/api/health");const b=await r.json();if(!r.ok)throw new Error("not ready");setStatus(b.provider_configured?"AI service connected":"Server needs API key",b.provider_configured?"ok":"error")}catch(e){setStatus("AI server not connected","error")}}
addRow("top");checkApi();updateCount();
